name: External Logs
description: Write logs to external storage
url: https://github.com/wbyoung/ha-external-logs
version: dev
slug: external_logs
arch:
  - amd64
  - aarch64
init: false
journald: true
options:
  directory: null
schema:
  directory: str
  wait_time: int?
map:
  - type: share
    read_only: false
