name: "External Logs"
description: "Write logs to external storage"
version: "1.0.0"
slug: "external_logs"
arch:
  - amd64
  - aarch64
init: false
image: "ghcr.io/wbyoung/{arch}-external_logs"
journald: true
options:
  directory: null
schema:
  directory: str
map:
  - type: share
    read_only: false
