---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  actions: read
  contents: write
  pull-requests: read
  packages: read
  security-events: write

jobs:
  workflows:
    name: App
    uses: wbyoung/ha-apps/.github/workflows/app-ci.yaml@main
