---
name: Deploy

on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  actions: read
  contents: write
  pull-requests: read
  packages: write
  security-events: write

jobs:
  ci:
    name: App
    uses: wbyoung/ha-apps/.github/workflows/app-ci.yaml@main

  deploy:
    needs: ci
    name: Deploy
    uses: wbyoung/ha-apps/.github/workflows/app-deploy.yaml@main
    with:
      repository: ha-apps
      repository_beta: ha-apps-beta
      repository_edge: ha-apps-edge
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
